README for running and testing - BackEnd
dylanlaffin/team1-api pull request #5
Opened 2024-07-23 11:03 UTC by dylanlaffin

The readme file updated to suit our project

2024-07-23 11:08 UTC, lexseaton approved these changes

2024-07-23 12:32 UTC, boydstepkainos commented on README.md
> +4. To check that your application is running enter url `http://localhost:3000`
Add a valid path for the project to the URL

2024-07-23 12:32 UTC, boydstepkainos submitted a review, later dismissed
There's sections left blank, such as technology. Please populate

2024-07-23 14:53 UTC, boydstepkainos commented on README.md
> +Front-End: IntelliJ, HTML, Docker, swagger, Css, Javascript
Don't need to list IDE's

2024-07-24 07:49 UTC, shaunganley requested changes

2024-07-24 07:49 UTC, shaunganley commented on README.md
> +4. To check that your application is running enter url `http://localhost:3000/loginForm`
this should be pointing to an api url

2024-07-24 07:49 UTC, shaunganley commented on README.md
> +Front-End: HTML, Docker, swagger, Css, Javascript
no need for frontend info in the api

2024-07-24 07:57 UTC, shaunganley approved these changes

2024-07-24 08:06 UTC, merged